document.writeln("	<div class=\'loginPop\'>");
document.writeln("		<div class=\'loginBox\'>");
document.writeln("			<span class=\'close\'>✖</span>");
document.writeln("			<h2>登录</h2>");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<input type=\'text\' placeholder=\'手机号\' class=\'text mobile\'>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<input type=\'password\' placeholder=\'密码\' class=\'text password\'>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<input type=\'password\' placeholder=\'原密码\' class=\'text oldPas\'>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<input type=\'password\' placeholder=\'新密码\' class=\'text password\'>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<div class=\'loginBtn\'>");
document.writeln("				<span>登录</span>");
document.writeln("				<span>确认</span>");
document.writeln("			</div>");
document.writeln("			<div class=\'loginCenter\'>");
document.writeln("				忘记密码？联系客服010-80220687");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'alertPop\'>");
document.writeln("		<div></div>");
document.writeln("	</div>");
document.writeln("	<div class=\'alertPop alertPop2\'>");
document.writeln("		<div></div>");
document.writeln("	</div>");