document.writeln("	<div class=\'footer\'>");
document.writeln("		<div class=\'main\'>");
document.writeln("			<div class=\'footerLeft\'>");
document.writeln("				<h2>400-060-2099</h2>");
document.writeln("				<dl>");
document.writeln("					<dt>");
document.writeln("						<br>邮箱：meiyu@xingguangedu.com<br>");
document.writeln("						微博：weibo@xingguangedu.com");
document.writeln("					</dt>");
document.writeln("					<dd>");
document.writeln("						<span>");
document.writeln("							<img src=\'images/ewm.jpg\' />");
document.writeln("							关注美育星光");
document.writeln("						</span>");
document.writeln("						<span>");
document.writeln("							<img src=\'images/ewmkt.jpg\' />");
document.writeln("							关注美育星光课堂");
document.writeln("						</span>");
document.writeln("					</dd>");
document.writeln("				</dl>");
document.writeln("			</div>");
document.writeln("			<div class=\'footerMap\'>");
document.writeln("				<img src=\'images/i_104.png\'>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'footerBottom\'>");
document.writeln("			<a href=\'material.html\'>教材&教参</a>");
document.writeln("			<a href=\'authentication.html\'>认证测评</a>");
document.writeln("			<a href=\'study.html\'>研学</a>");
document.writeln("			<a href=\'art.html\'>艺术节</a>");
document.writeln("			<a href=\'campus.html\'>戏剧校园</a>");
document.writeln("			<a href=\'partner.html\'>合作伙伴</a>");
document.writeln("			<a href=\'box.html\'>戏剧盒子</a>");
document.writeln("			<a href=\'about.html\'>关于我们</a>");
document.writeln("		</div>");
document.writeln("		<p>");
document.writeln("			北京美育星光网络科技有限公司 ©2018 All Rights reserved. <br>");
document.writeln("			京ICP备17014858号 ");
document.writeln("		</p>");
document.writeln("	</div>");